
version: '3.4'

services:
  auto-switch:
    build: .
    #image: mongo
    cap_add:
      - NET_ADMIN
      - NET_RAW

    #volumes:
    #  - /usr/lib/python3/docker_volume:/usr/lib/python3/docker_volume
    ports:
      - 6007:6007
