

FROM balenalib/raspberry-pi-debian-python:latest

WORKDIR /

COPY . .
# RUN pip install --no-cache-dir -r requirements.txt

CMD [ "python", "./web_flask.py" ]

# FROM ramyrr/auto-switches_auto-switch
# # python:latest
# # RUN apt-get update -y
# # WORKDIR /
# # /usr/local/bin/python
# #/var/lib/python/python_installed

# # COPY . .
# # RUN pip install --no-cache-dir -r requirements.txt
  

# CMD ["python", "./web_flask.py" ]    
# # CMD ["/script.sh"]

